version: 2
multi-ecosystem-groups:
  routine-dependencies:
    schedule:
      interval: weekly

updates:
  - package-ecosystem: npm
    directory: /
    patterns:
      - '*'
    open-pull-requests-limit: 1
    multi-ecosystem-group: routine-dependencies

  - package-ecosystem: github-actions
    directory: /
    patterns:
      - '*'
    open-pull-requests-limit: 1
    multi-ecosystem-group: routine-dependencies
