# These are supported funding model platforms

github: hadianr
# patreon: # your_patreon_username
# open_collective: # your_open_collective_username
# ko_fi: # your_ko_fi_username
# tidelift: # your_tidelift_platform/package-name
# community_bridge: # your_community_bridge_project
# liberapay: # your_liberapay_username
# issuehunt: # your_issuehunt_username
# otechie: # your_otechie_username
# lfx_crowdfunding: # your_lfx_crowdfunding_project
# custom: # your_custom_sponsorship_url
