# These are supported funding model platforms

github: hadianr
# patreon: # your_patreon_username
# open_collective: # your_open_collective_username
ko_fi: hadianr
custom: ["https://trakteer.id/hadianr", "https://buymeacoffee.com/hadianr"]
